version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - socket_server
      - db

  socket_server:
    build: ./socket_server
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
